# Generated by Django 4.0.6 on 2022-09-26 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('tipo', models.CharField(choices=[('HS', 'Hard Skill'), ('SS', 'Soft Skill')], max_length=2)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=65)),
                ('descricao', models.TextField()),
                ('link_repositorio', models.CharField(max_length=250)),
                ('link_site', models.CharField(blank=True, max_length=250, null=True)),
                ('tecnologias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.habilidades')),
            ],
        ),
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('sobrenome', models.CharField(max_length=250)),
                ('titulo', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.contatos')),
                ('habilidades', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.habilidades')),
                ('projetos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.projetos')),
            ],
        ),
    ]
