# Generated by Django 4.0.6 on 2022-09-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatos',
            new_name='Contato',
        ),
        migrations.RenameModel(
            old_name='Habilidades',
            new_name='Habilidade',
        ),
        migrations.RenameModel(
            old_name='Projetos',
            new_name='Projeto',
        ),
    ]
