# Generated by Django 4.0.6 on 2022-09-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_rename_contatos_contato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='contato',
        ),
        migrations.AddField(
            model_name='contato',
            name='desenvolvedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portifolio.desenvolvedor'),
        ),
    ]
