# Generated by Django 4.0.6 on 2022-09-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0003_remove_desenvolvedor_contato_contato_desenvolvedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='desenvolvedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='portifolio.desenvolvedor'),
        ),
    ]
