# Generated by Django 4.0.6 on 2022-09-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0004_alter_contato_desenvolvedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='desenvolvedor',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='habilidade',
            name='desenvolvedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilidades', to='portifolio.desenvolvedor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='desenvolvedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='portifolio.desenvolvedor'),
        ),
    ]
