# Generated by Django 4.0.6 on 2022-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0005_remove_desenvolvedor_habilidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='projetos',
            field=models.ManyToManyField(related_name='tecnologias', to='portifolio.projeto'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
