# Generated by Django 4.0.6 on 2022-09-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0006_habilidade_projetos_alter_habilidade_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='desenvolvedor',
            name='foto',
            field=models.ImageField(blank=True, default='', upload_to='dev/perfil/'),
        ),
    ]
