# Generated by Django 4.0.6 on 2022-09-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0007_desenvolvedor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidade',
            name='projetos',
            field=models.ManyToManyField(blank=True, related_name='tecnologias', to='portifolio.projeto'),
        ),
    ]
