# Generated by Django 4.0.6 on 2022-09-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0009_projeto_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='icone',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
