# Generated by Django 4.0.6 on 2022-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0010_habilidade_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='icone',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
